#!/bin/sh
set -e

echo "[ENTRYPOINT] Generating OpenAlgo .env..."

cat > /app/.env <<EOF
ENV_CONFIG_VERSION='1.0.7'

BROKER_API_KEY='${BROKER_API_KEY}'
BROKER_API_SECRET='${BROKER_API_SECRET}'

APP_KEY='${APP_KEY}'
API_KEY_PEPPER='${API_KEY_PEPPER}'
FERNET_SALT='${FERNET_SALT}'

DATABASE_URL='sqlite:///db/openalgo.db'
LATENCY_DATABASE_URL='sqlite:///db/latency.db'
LOGS_DATABASE_URL='sqlite:///db/logs.db'
HEALTH_DATABASE_URL='sqlite:///db/health.db'
SANDBOX_DATABASE_URL='sqlite:///db/sandbox.db'
HISTORIFY_DATABASE_URL='db/historify.duckdb'

HOST_SERVER='${HOST_SERVER}'
REDIRECT_URL='${REDIRECT_URL}'

FLASK_HOST_IP='0.0.0.0'
FLASK_PORT='5000'
FLASK_ENV='production'
FLASK_DEBUG='False'

WEBSOCKET_HOST='0.0.0.0'
WEBSOCKET_PORT='8765'
WEBSOCKET_URL='${WEBSOCKET_URL}'

TRUST_PROXY_HEADERS='TRUE'
NGROK_ALLOW='FALSE'

OPENBLAS_NUM_THREADS='2'
OMP_NUM_THREADS='2'
MKL_NUM_THREADS='2'
NUMEXPR_NUM_THREADS='2'
NUMBA_NUM_THREADS='2'
STRATEGY_MEMORY_LIMIT_MB='512'
EOF

echo "[ENTRYPOINT] .env generated"

exec ./start.sh